from __future__ import annotations

import os
import smtplib
from dataclasses import dataclass
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path


@dataclass
class EmailConfig:
    host: str
    port: int
    user: str
    password: str
    from_addr: str
    to_addrs: list[str]
    use_tls: bool = True

    @classmethod
    def from_env(cls) -> EmailConfig | None:
        to_raw = os.environ.get("EMAIL_TO", "")
        host = os.environ.get("SMTP_HOST", "")
        if not to_raw or not host:
            return None
        return cls(
            host=host,
            port=int(os.environ.get("SMTP_PORT", "587")),
            user=os.environ.get("SMTP_USER", ""),
            password=os.environ.get("SMTP_PASSWORD", ""),
            from_addr=os.environ.get("EMAIL_FROM", os.environ.get("SMTP_USER", "")),
            to_addrs=[a.strip() for a in to_raw.split(",") if a.strip()],
            use_tls=os.environ.get("SMTP_USE_TLS", "true").lower() != "false",
        )


def get_actionable_tickers(report: dict) -> list[dict]:
    return [t for t in report.get("tickers", []) if t.get("tier") in ("Tier 1", "Tier 2")]


def build_actionable_email(
    report: dict,
    *,
    scan_date: date | None = None,
    archive_dir: Path | None = None,
) -> tuple[str, str]:
    """Return (subject, html_body) for actionable tickers email."""
    scan_date = scan_date or date.today()
    summary = report["scan_summary"]
    regime = report["market_regime"]
    tiers = summary["tier_counts"]
    actionable = get_actionable_tickers(report)

    subject = (
        f"Breakout Scan {scan_date:%Y-%m-%d}: "
        f"{len(actionable)} actionable "
        f"({tiers['Tier 1']} Tier 1, {tiers['Tier 2']} Tier 2)"
    )

    rows_html = ""
    for t in sorted(actionable, key=lambda x: x["summary"]["final_adjusted_score"], reverse=True):
        s = t["summary"]
        scores = t.get("scores") or {}
        rs = scores.get("rs_market", {}).get("score", "-")
        comp = scores.get("compression", {}).get("score", "-")
        vol = scores.get("relative_volume", {}).get("score", "-")
        rows_html += f"""
        <tr>
          <td><strong>{t['ticker']}</strong></td>
          <td>{t['tier']}</td>
          <td>{s.get('final_adjusted_score', 0):.1f}</td>
          <td>{t.get('sector_etf', '')}</td>
          <td>{rs}</td>
          <td>{comp}</td>
          <td>{vol}</td>
          <td>{t.get('tier_reason', '')}</td>
        </tr>"""

    if not rows_html:
        rows_html = '<tr><td colspan="8">No actionable tickers today (Tier 1 or Tier 2).</td></tr>'

    archive_note = f"<p>Archived to: <code>{archive_dir}</code></p>" if archive_dir else ""

    html = f"""
    <html><body style="font-family: sans-serif; color: #222;">
    <h2>Breakout Scan — {scan_date:%Y-%m-%d}</h2>
    <p><strong>Market regime:</strong> {regime['label'].title()} (×{regime['multiplier']}) —
    SPY ${regime['spy_price']}, 63d return {regime['return_63d_pct']}%</p>
    <p><strong>Universe:</strong> {summary['universe_size']} tickers |
    <strong>Eligible:</strong> {summary['eligible_count']} |
    <strong>Actionable:</strong> {len(actionable)}</p>
    {archive_note}
    <h3>Actionable Tickers (Tier 1 and Tier 2)</h3>
    <table border="1" cellpadding="6" cellspacing="0"
           style="border-collapse: collapse; width: 100%;">
      <thead style="background: #f0f0f0;">
        <tr>
          <th>Ticker</th><th>Tier</th><th>Score</th><th>Sector ETF</th>
          <th>RS Mkt</th><th>Compress</th><th>Rel Vol</th><th>Reason</th>
        </tr>
      </thead>
      <tbody>{rows_html}</tbody>
    </table>
    <h3>Component detail (top actionable)</h3>
    {_component_details_html(actionable[:5])}
    <p style="color: #666; font-size: 12px;">
      Generated by quant-platform. Tier 1 = breakout ready. Tier 2 = watchlist.
    </p>
    </body></html>
    """
    return subject, html


def _component_details_html(tickers: list[dict]) -> str:
    if not tickers:
        return "<p>None</p>"
    parts = []
    for t in tickers:
        lines = [f"<strong>{t['ticker']}</strong> ({t['tier']})"]
        scores = t.get("scores") or {}
        for name, comp in scores.items():
            label = name.replace("_", " ").title()
            meaning = comp.get("meaning", "")
            lines.append(f"&nbsp;&nbsp;{label}: {comp.get('score')}/{comp.get('max')} — {meaning}")
        parts.append("<p>" + "<br>".join(lines) + "</p>")
    return "\n".join(parts)


def send_scan_email(
    report: dict,
    *,
    config: EmailConfig | None = None,
    scan_date: date | None = None,
    archive_dir: Path | None = None,
) -> bool:
    """Send actionable tickers email. Returns True if sent."""
    config = config or EmailConfig.from_env()
    if not config:
        return False

    subject, html = build_actionable_email(report, scan_date=scan_date, archive_dir=archive_dir)
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = config.from_addr
    msg["To"] = ", ".join(config.to_addrs)
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP(config.host, config.port, timeout=30) as server:
        if config.use_tls:
            server.starttls()
        if config.user and config.password:
            server.login(config.user, config.password)
        server.sendmail(config.from_addr, config.to_addrs, msg.as_string())

    return True
